### ISSUE TITLE
建议添加搜索跳转

### ISSUE THREAD

**Issue by thunder1GG** [LukeReader/luke-novel-reader#11]
现在我有本小说，只识别到个别章节目录，我已经看到后面，因为章节只识别到了前面几十章，现在想看后面的跳转不了

**Comment by LukeReader** [comment]
你好，方便上传下你的小说吗，我适配下识别目录的规则

**Comment by thunder1GG** [comment]
我是雷霆，你的来信我已收到

**Comment by thunder1GG** [comment]
[从射箭开始修行.txt](https://github.com/user-attachments/files/17178695/default.txt)
看看这个，我只能解析出2到68章

**Comment by LukeReader** [comment]
好的，这个问题我们已经修复。您现在可以按照以下的步骤生成新的小说目录：
1. 确保当前插件是最新版本
2. 重启IDEA
3. 修改一个不同的小说文件名，重新双击生成目录

另外，会有些识别到重复章节的问题，这个是由于您的小说文件本身有重复。
> ***@***.***>
> 时间： 2024年9月29日 (周日) 17:22
> 主题： Re: [LukeReader/luke-novel-reader] 建议添加搜索跳转 (Issue #11)
> ***@***.***>
> ***@***.***>, ***@***.***>
> 从射箭开始修行.txt<https://github.com/user-attachments/files/17178695/default.txt>
> 
看看这个，我只能解析出2到68章

**Comment by thunder1GG** [comment]
我是雷霆，你的来信我已收到
