### ISSUE TITLE
点击目录没反应

### ISSUE THREAD

**Issue by yelaifeng** [LukeReader/luke-novel-reader#12]
[1.txt](https://github.com/user-attachments/files/17388019/1.txt)
![Snipaste_2024-10-16_09-42-05](https://github.com/user-attachments/assets/c43560aa-601e-4b3e-a37b-2a28a5b121ab)

**Comment by LukeReader** [comment]
你好，你的截图不全所以没法定位问题，请按下面的步骤排查一下：
1.确认左下角是否显示了导航栏，如果是的话，按照下面方法调整导航栏到顶部：编译器里 点击 View > Appearance > Navigation Bar > Top ，导航栏会调整到顶部。
2.如果导航栏没有问题，左下角展示 '<<'，说明当前是隐藏模式，双击右下角的 '<<<' 按钮即可切换到正常模式
3.如果还是不行，请提供一个完整的页面截图【注意打码您的隐私信息】
