### ISSUE TITLE
目录识别不准确

### ISSUE THREAD

**Issue by wuqi0606** [LukeReader/luke-novel-reader#2]
目录识别不准确，有好多正文信息
![tu](https://github.com/LukeReader/luke-novel-reader/assets/113758175/e72733f7-8962-4429-906f-fe11ac570553)

**Comment by LukeReader** [comment]
是否可以粘贴一段识别错误的文本，方便我修复后测试

**Comment by wuqi0606** [comment]
> 是否可以粘贴一段识别错误的文本，方便我修复后测试

　　她伸出手，轻轻放在自己胸膛，飞舞的冰雪之间，那双眼眸精芒闪烁：
　　“阿拙生前为我受尽了世人折磨……他与我融为一体后，我绝不会让他受到半点委屈！我公羊婉，一定要带着他，站上这个世界的顶端！！”


第1681章 我找到你了
　　看着风雪中的公羊婉，林七夜长叹了一口气。
　　公羊婉变成这样的原因，他大概是了解了，他也未曾想到，在国运岛屿时见到的那位温婉的公羊婉前辈，竟然有这样一段悲惨辛酸的过去。

**Comment by LukeReader** [comment]
更新了一版，试下最新的1.0.5是否可以
