### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by liaokaiwei** [LukeReader/luke-novel-reader#3]
idea 2024 不能用吗，为啥我点击章节没有反应

**Comment by LukeReader** [comment]
看下左下角是否显示了导航栏，如果是的话，需要设置一下调整导航栏到顶部。
调整的方式：编译器里 点击 View > Appearance > Navigation Bar > Top ，导航栏会调整到顶部。
调整好之后，左下角是小说内容，左上角是导航栏。
设置好之后选择目录，单击右下角>>>翻页，双击>>>是隐藏。


如果不是这个问题，提供下截图我看下原因
