### ISSUE TITLE
idea 2024.1.3 加载不出小说文字内容

### ISSUE THREAD

**Issue by retroxz** [LukeReader/luke-novel-reader#4]
打开小说文本之后 左下角能正常显示一局 点击>>>按钮后 仅显示>>

刚安装上的时候是可以正常显示的 翻了十几章之后就只会显示>> 

再返回之前正常的章节 也无法显示文字内容

**Comment by LukeReader** [comment]
是否不小心双击了，双击是快速隐藏，再次双击即可恢复

**Comment by retroxz** [comment]
哦哦 是的 谢谢
